common: &common
  adapter: postgresql
  encoding: unicode
  username: sampleapp
  password: sampleapp

development:
  <<: *common
  database: sampleapp_development

test:
  <<: *common
  database: sampleapp_test

production:
  <<: *common
  database: sampleapp_production
